openapi: 3.0.3
info:
  title: Health-Route
  description: Health-Route
  version: 1.0.0
servers:
  - url: 'localhost:8080/api/v1'
paths:
  /meals:
    get:
      summary: Returns a list of all Meals
      responses:
        '200':
          description: A JSON array of meals
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Meal'
    post:
      summary: Create a new Meal
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                timestamp:
                  type: string
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request, failed to create Meal
  /meals/{mealId}:
    get:
      summary: Get a meal by it's ID.
      parameters:
        - in: path
          name: mealId
          schema:
            type: integer
          required: true
          description: The Numeric ID of the meal being retrieved.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Meal'
  /foods:
    get:
      summary: Returns a list of all Foods
      responses:
        '200':
          description: A JSON Array of Foods
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Food'
    post:
      summary: Create a new Food.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                mealId:
                  type: integer
                name:
                  type: string
                calories:
                  type: integer
                carbohydrates:
                  type: integer
                protein:
                  type: integer
                fat:
                  type: integer
      responses:
        '201':
          description: Created.
        '400':
          description: Bad Request.
  /foods/{foodId}:
    get:
      summary: Get a food by ID
      parameters:
        - in: path
          name: foodId
          schema:
            type: integer
          required: true
          description: Numeric ID of the food to get.
      responses:
        '200':
          description: A food object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Food'
        '400':
          description: The specified food ID is invalid or not a number.
        '404':
          description: A food with the specified ID was not found.
    delete:
      summary: Delete a food
      parameters:
        - in: path
          name: foodId
          schema:
            type: integer
          required: true
          description: Numeric ID of the food to delete.
      responses:
        '200':
          description: Food successfully deleted.
        '404':
          description: Food could not be found.
  /foods/meal/{mealId}:
    get:
      summary: Get all foods for a specified meal
      parameters:
        - in: path
          name: mealId
          schema:
            type: integer
          required: true
          description: Numeric ID of the meal whose foods are being retrieved.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Food'
  /foods/{foodId}/{mealId}:
    patch:
      summary: Add a Food to a Meal.
      parameters:
        - in: path
          name: foodId
          schema:
            type: integer
          required: true
          description: Numeric ID for a Food.
        - in: path
          name: mealId
          schema:
            type: integer
          required: true
          description: Numeric ID for a Meal.
      responses:
        '200':
          description: Food successfully added to Meal.
  /medications:
    get:
      summary: Retrieve all Medications.
      responses:
        '200':
          description: A list of Medications
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Medication'
  /day:
    get:
      summary: Retrieve all DailyLogs.
      responses:
        '200':
          description: A list of DailyLogs.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DailyLog'
    post:
      summary: Create a new Day.
      responses:
        '201':
          description: Successfully created a new Day.
components:
  schemas:
    Food:
      type: object
      properties:
        food_id:
          type: integer
        mealId:
          type: integer
        name:
          type: string
        calories:
          type: integer
          example: 280
        carbohydrates:
          type: integer
          example: 16
        protein:
          type: integer
          example: 14
        fat:
          type: integer
          example: 32
    Meal:
      type: object
      properties:
        meal_id:
          type: integer
        timestamp:
          type: string
          format: date-time
          example: 2022-07-05T13:12:40Z
    Medication:
      type: object
      properties:
        medication_id:
          type: integer
        name:
          type: string
          example: Prednisone
        quantity:
          type: integer
          example: 1
        strength:
          type: integer
          example: 20
        dosage_unit:
          type: string
          example: mg
    DailyLog:
      type: object
      properties:
        dailylog_id:
          type: integer
        meals:
          type: array
          items:
            $ref: '#/components/schemas/Meal'
        date:
          type: string
          format: date
          example: 2022-07-05